spring:
  config:
    import: optional:file:./server/.env.properties

  application:
    name: tickets

  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: dev
springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

---
spring:
  config:
    activate:
      on-profile: prod
springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false