services:
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8888:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=host.docker.internal   # Cho Windows/Mac
    
  keycloak:
    image: keycloak/keycloak:latest
    ports:
      - "9090:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - keycloak_data:/opt/keycloak/data
    command:
      - start-dev
      - --db=dev-file

volumes:
  keycloak_data:
    driver: local
